console.log('' + 1 + 0);        // ผลลัพธ์: "10" (การเชื่อมต่อกับ String)
console.log('' - 1 + 0);        // ผลลัพธ์: -1 (การลบ String ที่ว่างไปจากตัวเลข)
console.log(true + false);       // ผลลัพธ์: 1 (true แปลงเป็น 1, false แปลงเป็น 0)
console.log(6 / '3');           // ผลลัพธ์: 2 (String '3' ถูกแปลงเป็นตัวเลข)
console.log('2' * '3');         // ผลลัพธ์: 6 (String '2' และ '3' ถูกแปลงเป็นตัวเลข)
console.log('  -9  ' - 5);      // ผลลัพธ์: -14 (String '  -9  ' ถูกแปลงเป็นตัวเลข)
console.log('  -9  ' + 5);      // ผลลัพธ์: "  -9 5" (การเชื่อมต่อกับ String)
console.log('4px' - 2);         // ผลลัพธ์: NaN (String '4px' ไม่สามารถแปลงเป็นตัวเลขได้)
console.log(2 + 4 + 'px');      // ผลลัพธ์: "6px" (การเชื่อมต่อกับ String)
console.log(null + 1);          // ผลลัพธ์: 1 (null ถูกแปลงเป็น 0)
console.log(undefined + 1);     // ผลลัพธ์: NaN (undefined ไม่สามารถเปลี่ยนเป็นตัวเลขได้)
